---
jobs:  
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-concourse-build-docker-image
    trigger: true
  - put: docker-image
    params:
      build: git-concourse-build-docker-image/ci

resources:  
- name: git-concourse-build-docker-image
  type: git
  source:
    uri: git@github.com:opencontrol/concourse-spruce-task.git
    branch: master
